[package]
name = "bare-minimum-rust"
version = "0.0.1"
authors = ["Brandon Matthews <bmatthews@zipcar.com>"]

[dependencies]
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }
